### PR TITLE
Result builder fixes

### PR DESCRIPTION
**Pull request by tonyarnold**
This PR proposes to update the ContentBuilder to support partial blocks. This seems to resolve the issues that I was seeing with #132, and potentially other unexpectedly invalid content combinations.

Sorry for the lack of comment documentation on these revised methods. 

I've also included conformance of the `Link` type to `BodyElement` as it's valid HTML.

### CODE REVIEW

**Comment by mattesmohr** [comment]
Haha, I was looking into this yesterday too. But you seem to be faster than me.

**Comment by mattesmohr** [comment]
My sites are doing fine with your result builder. Great job! 

I do not understand every line of your code yet and I want to, before I merge it, if that's okay?

What were the reasons for removing the comments? Not helpful enough?

**Comment by mattesmohr** [comment]
I would add those tests too, so we can be sure we take your cases into account for future changes.

```swift
    func testOptionalAfterElement() throws {
        
        let name: String? = "Tony"
        
        let view = TestView {
            Division {
            }
            if let name = name {
                Paragraph {
                    name
                }
            }
        }
        
        XCTAssertEqual(try renderer.render(view: view),
                       """
                       <div></div>\
                       <p>Tony</p>
                       """
        )
    }
    
    func testOptionalBeforeElement() throws {
        
        let name: String? = "Tony"
        
        let view = TestView {
            if let name = name {
                Paragraph {
                    name
                }
            }
            Division {
            }
        }
        
        XCTAssertEqual(try renderer.render(view: view),
                       """
                       <p>Tony</p>\
                       <div></div>
                       """
        )
    }
    
    func testOptionalWithExpectedResult() throws {
        
        let name: String? = "Tony"
        
        let view = TestView {
            Body {
                if let name = name {
                    Paragraph {
                        name
                    }
                }
            }
        }
        
        XCTAssertEqual(try renderer.render(view: view),
                       """
                       <body>\
                       <p>Tony</p>\
                       </body>
                       """
        )
    }
``

**Comment by tonyarnold** [comment]
> I do not understand every line of your code yet, but I want to, before I merge it, if that's okay?

Of course, take your time!

> What were the reasons for removing the comments? Not helpful enough?

I started over, and was doing it at the dinner table with my kids underfoot. I honestly didn't have time to test each method in the result builder this evening, so I just sent it through as a PR as-is. 

I think the comments should be added before merging this — I just don't have time to do it this evening :)

**Comment by mattesmohr** [comment]
No problem. I hope it's okay, I intervene/interfere in your PR. I have added some real quick, because I do not know if I have time for it tomorrow.

**Comment by mattesmohr** [comment]
I could break it down to those view functions. Can you check if it works for you too?

```swift
// Abstract:
// The file contains the builder to build up the result from a sequence of elements.

/// The builder builds up a result value from a sequence of elements.
@resultBuilder public enum ContentBuilder<T> {
    
    public typealias Component = [T]
    
    public typealias Expression = T

    /// Builds an empty block
    ///
    /// ```swift
    /// Tag {
    /// }
    /// ```
    public static func buildBlock() -> Component {
        return []
    }
    
    /// Builds a block with one element.
    ///
    /// ```swift
    /// Tag {
    ///    Tag {
    ///    }
    /// }
    /// ```
    public static func buildPartialBlock(first: Component) -> Component {
        return first
    }

    /// Builds a block with more than one element.
    ///
    /// ```swift
    /// Tag {
    ///    Tag {
    ///    }
    ///    Tag {
    ///    }
    /// }
    /// ```
    public static func buildPartialBlock(accumulated: Component, next: Component) -> Component {
        return accumulated + next
    }

    /// Builds a block
    ///
    /// ```swift
    /// let content = "Content"
    ///
    /// Tag {
    ///    content
    /// }
    /// ```
    public static func buildExpression(_ element: Expression?) -> Component {
        
        guard let element else {
            return []
        }
        return [element]
    }
    
    /// Builds a block
    ///
    /// ```swift
    /// let content: [Type]
    ///
    /// Tag {
    ///    content
    /// }
    /// ```
    public static func buildExpression(_ element: Component) -> Component {
        return element
    }

    /// Builds a block with one element.
    ///
    /// ```swift
    /// Tag {
    ///    if let unwrapped = optional {
    ///       Tag {
    ///          unwrapped
    ///       }
    ///    }
    /// }
    /// ```
    public static func buildOptional(_ component: Component?) -> Component {

        guard let component else {
            return []
        }
        return component
    }

    /// Builds a block, if the condition is true.
    ///
    /// ```swift
    /// Tag {
    ///    if(true) {
    ///       Tag {
    ///       }
    ///    }
    /// }
    /// ```
    public static func buildEither(first: Component) -> Component {
        return first
    }

    /// Builds a block, if the condition is false.
    ///
    /// ```swift
    /// Tag {
    ///    if(false) {
    ///       Tag {
    ///       }
    ///    }
    ///    else {
    ///       Tag {
    ///       }
    ///    }
    /// }
    /// ```
    public static func buildEither(second: Component) -> Component {
        return second
    }

    /// Builds blocks by running through a sequence of elements.
    ///
    /// ```swift
    /// Tag {
    ///    for element in sequence {
    ///       Tag {
    ///          element
    ///       }
    ///    }
    /// }
    /// ```
    public static func buildArray(_ components: [Component]) -> Component {
        return components.flatMap { $0 }
    }
}


```

**Comment by mattesmohr** [comment]
@tonyarnold Hiya, could you find some time to copy paste the result builder I have posted into your project to see if it works for you too?

**Comment by tonyarnold** [comment]
Hi @mattesmohr! I've just tied your suggested amendments, and they seem to work for me, too - no compilation errors, and everything seems to be rendering as it did with my earlier revision.

**Comment by tonyarnold** [comment]
Would you like me to update this PR with those changes, or are you happy to do that?

**Comment by mattesmohr** [comment]
Awesome! Thank your for testing. Don't bother. Consider it as done.

**Review by mattesmohr — APPROVED** [review]
Awesome! Thank your for testing. Don't bother. Consider it as done.

I suggest you run your project against the alpha.6 branch, so you will have both changes at the same time now. The changes of the result builder and the conditions attributes.

**Pull request merged**
