### PR TITLE
Correct spelling, add missing case and fix a html tag

### PR DESCRIPTION
**Pull request by mattesmohr**
I forgot to correct the .environment spelling in the Readme file in the first place, so I changed it now. Also I corrected the spelling accordingly the issues #26 and changed it in the Readme file either. 

I have added the missing option "reset" for the Button tag.

The Audio tag hadn't the right tag name yet.

### CODE REVIEW

**Comment by mattesmohr** [comment]
@MatsMoll Sorry, to bother you again. Seems I have no write access for an instant merge or release.

**Comment by MatsMoll** [comment]
Sorry for the late reply, but thanks for the PR! 
I also think you might need to be part of the vapor-community organization in order to get write access. However, the PR looks good. 
So again thanks for the improvements 🤩

**Comment by mattesmohr** [comment]
@MatsMoll thanks! What do think will be the best for the future to let you know? 

Not sure if you get a notifications about incoming PRs.

Should I ping you here or leave you a message on discord? 

I am planning do make more commits before requesting a merge in the future. 

Do not want to annoy you.

Maybe you find some time to take look into the discussions. I opened a thread there.

Cheers

**Comment by MatsMoll** [comment]
Keep adding all PRs you want, I am just happy to see them coming! 😄 so you don't need to be afraid that I will get annoyed.

And I get notified through email. But I might be a bit slow to look at them, as I mainly work on other projects as of now. However, if you feel I use too long to comment or approve. Then definitely send me a message on discord as well!

And good that you mention the discussion, as I thought I had answered it for some reason. So I will check it out

But contribution in any way helps a lot, so keep it coming! 🤩

**Pull request merged**
