### PR TITLE
[WIP] Feature/vapor 4 compatibility

### PR DESCRIPTION
**Pull request by siemensikkema**

### CODE REVIEW

**Comment by siemensikkema** [comment]
@MatsMoll Hi! I've been experimenting with HTML 2.0 and Vapor 4 a bit. I really like it so far! What surprised me a bit was the lack of type safety around attributes. For example, it's possible to add the "method" attribute to nodes other than forms. Have you thought about limiting which attributes to be applicable to which elements so it's harder to make invalid HTML?

**Comment by MatsMoll** [comment]
Hi @siemensikkema! First of all thanks for the PR! It looks good, so thanks for the help. 

The answer to your question is a yes in some ways. I have thought about it, but I have never implemented it as I was unsure about all the contexts to use the attributes in, and I therefore ended up going the easy route and allowing all of them everywhere. So i went for a "to flexible" solution in stead of a "to strict". But it would be an awesome addition to limit the options more where it makes sens.
So I guess it could be possible to add some protocols for each, or a collection of attributes.

Or what do you think?

In case you haven't seen the `AttributeNode` protocol, this will implement a lot of the attributes as long as you have a variable called `attributes` and a method called `copy(with attributes:)`.

**Comment by siemensikkema** [comment]
@MatsMoll yeah that's the approach I was considering. I might have to make a big matrix or something to figure out which attributes are legal for which nodes and distill some protocols from that.
I'm eager to see this library be ready and even greater for Vapor 4 and I'm willing to help out where I can. I am investigating replacing leaf for our packages and projects and I think this package looks great for that purpose.

**Comment by MatsMoll** [comment]
@siemensikkema that sounds like a good idea, and I like to help on the matrix if possible. But I am currently very limited on time, so the time used on HTMLKit can vary a lot. So any help will be very much appreciated

**Pull request merged**
